### ISSUE TITLE
无论数据提交多久，1min,5min和15min的数据都是一样的

### ISSUE THREAD

**Issue by zhengyangyong** [imdada/overwatch#4]
起客户端每隔5秒上传调用数据，rpm大小随机，运行超过15min后，按理论1min,5min和15min的统计数据应该是不一样的，结果是永远保持一样

**Comment by ZstringX** [comment]
上传的调用数据中有个时间戳字段，该字段应该是一个unix timestamp（精确到秒）
我暂时没有重现这个问题，是否可以提供一下测试数据？

**Comment by zhengyangyong** [comment]
已修复

**Comment by ZstringX** [comment]
由于根据分钟聚合数据，所以使用/stats/接口上传数据时需要保证数据为按分钟聚合的数据，如数据是按秒聚合的则可能出现类似的问题。现已改进为按秒聚合。
